### PR TITLE
#268 allow duck db to use existing database file

### LINKED ISSUE #268: DuckDB Plugin cannot use a DB file from the current WorkingDirectory
### Feature description

Use case: you ingest or transform data with DuckDB in one task and you want to use it in a downstream task within children tasks of `WorkingDirectory`:
- ✅ Doing it in Python works
- ❌ Doing it in kestra DuckDB plugin doesn't work

See the example below where the Python task just works and the DuckDB plugin fails:

```yaml
id: dbt_duckdb
namespace: blueprint

variables:
  db: "dbt.duckdb"

tasks:
  - id: dbt
    type: io.kestra.core.tasks.flows.WorkingDirectory
    tasks:
    - id: cloneRepository
      type: io.kestra.plugin.git.Clone
      url: https://github.com/kestra-io/dbt-demo
      branch: main

    - id: dbt-build
      type: io.kestra.plugin.dbt.cli.DbtCLI
      outputFiles:
        - db.duckdb
      runner: DOCKER
      docker:
        image: ghcr.io/kestra-io/dbt-duckdb:latest
      commands:
        - dbt deps
        - dbt build
      profiles: |
        jaffle_shop:
          outputs:
            dev:
              type: duckdb
              path: "{{ vars.db }}"
              extensions: 
                - parquet
              fixed_retries: 1
              threads: 16
              timeout_seconds: 300
          target: dev

    - id: python
      type: io.kestra.plugin.scripts.python.Script
      outputFiles:
        - "*.csv"
      docker:
        image: ghcr.io/kestra-io/duckdb:latest
      script: |
        import duckdb
        import pandas as pd

        conn = duckdb.connect(database="{{ vars.db }}")

        tables_query = "SELECT table_name FROM information_schema.tables WHERE table_schema = 'main';"
        tables = conn.execute(tables_query).fetchall()

        # Export each table to CSV, excluding tables that start with 'raw' or 'stg'
        for table_name in tables:
            table_name = table_name[0]
            # Skip tables with names starting with 'raw' or 'stg'
            if not table_name.startswith('raw') and not table_name.startswith('stg'):
                query = f"SELECT * FROM {table_name}"
                df = conn.execute(query).fetchdf()
                df.to_csv(f"{table_name}.csv", index=False)

        conn.close()

    - id: query
      type: io.kestra.plugin.jdbc.duckdb.Query
      url: jdbc:duckdb:dbt.duckdb
      sql: SELECT table_name FROM information_schema.tables WHERE table_schema = 'main';
      store: true
      allowFailure: true

    - id: query1
      type: io.kestra.plugin.jdbc.duckdb.Query
      url: "jdbc:duckdb:{{ vars.db }}"
      sql: SELECT table_name FROM information_schema.tables WHERE table_schema = 'main';
      store: true
      allowFailure: true

    - id: query2
      type: io.kestra.plugin.jdbc.duckdb.Query
      url: jdbc:duckdb:{{workingDir}}/dbt.duckdb
      sql: SELECT table_name FROM information_schema.tables WHERE table_schema = 'main';
      store: true      
      allowFailure: true
      
    - id: query3
      type: io.kestra.plugin.jdbc.duckdb.Query
      url: jdbc:duckdb:./dbt.duckdb
      sql: SELECT table_name FROM information_schema.tables WHERE table_schema = 'main';
      store: true      
      allowFailure: true      
```

### PR DESCRIPTION
**Pull request by iNikitaGricenko**
### What changes are being made and why?

- Closes #268. Allowing duckdb to use existing db file
---

### How the changes have been QAed?

```yaml
variables:
  db: "duck.db"

tasks:
- id: query1
  type: io.kestra.plugin.jdbc.duckdb.Query
  url: jdbc:duckdb:/{{ vars.db }}
  sql: SELECT table_name FROM information_schema.tables WHERE table_schema = 'main';
  store: true
  allowFailure: true
  
- id: query2
  type: io.kestra.plugin.jdbc.duckdb.Query
  url: jdbc:duckdb:/duck.db
  sql: SELECT table_name FROM information_schema.tables WHERE table_schema = 'main';
  store: true
  allowFailure: true
```

### CODE REVIEW

File: plugin-jdbc-duckdb/src/main/java/io/kestra/plugin/jdbc/duckdb/Query.java [hunk 1]
```diff
@@ -97,6 +98,9 @@ public class Query extends AbstractJdbcQuery implements RunnableTask<Query.Outpu
     @PluginProperty(dynamic = true)
     private String url = DEFAULT_URL;
 
+    @Getter(AccessLevel.NONE)
+    protected transient Path workingDirectory;
```
Comment (loicmathieu) [inline plugin-jdbc-duckdb/src/main/java/io/kestra/plugin/jdbc/duckdb/Query.java:102]: It seems the `wokingDirectory` is only used by the run method, in this case this can be a variable in it instead of a class attribute.

**Review by loicmathieu — CHANGES_REQUESTED** [review]
Can you add an example in the `@Plugin` annotation with the usage of a database file?

File: plugin-jdbc-duckdb/src/main/java/io/kestra/plugin/jdbc/duckdb/Query.java [hunk 2]
```diff
@@ -61,6 +62,48 @@
                 "    outputFiles:",
                 "       - out"
             }
+        ),
+        @Example(
+            title = "Execute a query that reads from existing database file using url only.",
```
Comment (loicmathieu) [inline plugin-jdbc-duckdb/src/main/java/io/kestra/plugin/jdbc/duckdb/Query.java:67]:
```suggestion
            title = "Execute a query that reads from an existing database file using a URL.",
```

File: plugin-jdbc-duckdb/src/main/java/io/kestra/plugin/jdbc/duckdb/Query.java [hunk 3]
```diff
@@ -61,6 +62,48 @@
...
+                "",
+                "  - id: query2",
+                "    type: io.kestra.plugin.jdbc.duckdb.Query",
+                "    url: jdbc:duckdb:/temp/folder/duck.db",
+                "    sql: SELECT * FROM table_name;",
+                "    store: true"
+            }
+        ),
+        @Example(
+            title = "Execute a query that reads from existing database file using databaseFile variable.",
```
Comment (loicmathieu) [inline plugin-jdbc-duckdb/src/main/java/io/kestra/plugin/jdbc/duckdb/Query.java:87]:
```suggestion
            title = "Execute a query that reads from an existing database file using the `databaseFile` variable.",
```

**Review by loicmathieu — APPROVED** [review]
LGTM, I added two small doc modification that I'll commit before merging.

**Comment by loicmathieu** [comment]
Merging it as test fail in an unrelated plugin
